import { useCallback, useEffect, useMemo, useState } from 'react'
import { io } from 'socket.io-client'
import { apiRequest, endSession, refreshSession, SOCKET_URL, type SessionResult, type SessionUser } from './api'
import { Icon } from './icons'
import './App.css'

type Role = SessionUser['role']
type Status = 'TODO' | 'IN_PROGRESS' | 'IN_REVIEW' | 'DONE'
type Priority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
type View = 'dashboard' | 'projects' | 'tasks' | 'clients' | 'users' | 'activity'
type Filters = { status: '' | Status; priority: '' | Priority; dueFrom: string; dueTo: string }
type ApiTask = { id: string; number: number; projectId: string; assignedDeveloperId: string; title: string; description: string; status: Status; priority: Priority; dueAt: string; isOverdue: boolean; version: number; project: { id: string; name: string; createdById: string }; assignedDeveloper: { id: string; name: string; email: string } }
type ApiProject = { id: string; name: string; description: string; client: { id: string; name: string }; createdBy: { id: string; name: string }; _count: { tasks: number } }
type ApiClient = { id: string; name: string; contactName?: string; contactEmail?: string; _count?: { projects: number } }
type ApiDeveloper = { id: string; name: string; email: string }
type ApiActivity = { id: string; sequence: string; type: string; fromStatus?: Status; toStatus?: Status; createdAt: string; metadata?: Record<string, unknown>; actor?: { name: string } | null; task?: { number: number; title: string } | null; project: { id: string; name: string } }
type ApiNotification = { id: string; type: 'TASK_ASSIGNED' | 'TASK_IN_REVIEW'; readAt: string | null; createdAt: string; task: { number: number; title: string }; activityEvent: { createdAt: string } }
type ApiDashboard = { projectCount: number; taskCount: number; overdueCount: number; byStatus: Record<Status, number>; byPriority: Record<Priority, number>; upcoming: Array<{ id: string; number: number; title: string; dueAt: string; priority: Priority; status: Status }>; onlineUsers?: number }
type ApiUser = SessionUser & { isActive: boolean }
type MemberRequest = { id: string; name: string; email: string; reason: string; status: 'PENDING' | 'APPROVED' | 'REJECTED'; createdAt: string; requestedBy: { name: string } }

const statusLabel = (value: Status) => value.replaceAll('_', ' ')
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase()
const relativeTime = (value: string) => {
  const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000))
  if (seconds < 60) return `${seconds}s ago`
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`
  return `${Math.floor(seconds / 86400)}d ago`
}
const activityText = (event: ApiActivity) => {
  const task = event.task ? `Task #${event.task.number}` : event.project.name
  if (event.type === 'STATUS_CHANGED') return `moved ${task} from ${statusLabel(event.fromStatus!)} to ${statusLabel(event.toStatus!)}`
  if (event.type === 'TASK_ASSIGNED') return `assigned ${task}`
  if (event.type === 'TASK_OVERDUE') return `flagged ${task} as overdue`
  if (event.type === 'PROJECT_CREATED') return `created project ${event.project.name}`
  return `updated ${task}`
}
const queryFor = (filters: Filters) => {
  const params = new URLSearchParams()
  for (const [key, value] of Object.entries(filters)) if (value) params.set(key, value)
  params.set('pageSize', '100')
  return params.toString()
}
const filtersFromUrl = (): Filters => { const p = new URLSearchParams(location.search); return { status: (p.get('status') as Filters['status']) || '', priority: (p.get('priority') as Filters['priority']) || '', dueFrom: p.get('dueFrom') || '', dueTo: p.get('dueTo') || '' } }

function Avatar({ name }: { name: string }) { return <span className="avatar avatar--dark">{initials(name)}</span> }
function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: string }) { return <span className={`badge badge--${tone}`}>{children}</span> }
function Logo() { return <div className="brand"><span className="brand-mark">V</span><div><strong>VELOZITY</strong><small>PROJECT DESK</small></div></div> }

function Login({ onLogin }: { onLogin: (session: SessionResult) => void }) {
  const [email, setEmail] = useState('maya@velozity.dev'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const demos = [
    ['Administrator', 'anika@velozity.dev', 'ChangeMe-Admin-2026!'],
    ['Project manager', 'maya@velozity.dev', 'ChangeMe-PM-2026!'],
    ['Developer', 'aarav@velozity.dev', 'ChangeMe-Developer-2026!'],
  ] as const
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { onLogin(await apiRequest<SessionResult>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) })) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Login failed.') } finally { setBusy(false) } }
  return <main className="auth-page"><section className="auth-story"><Logo/><div className="auth-copy"><span className="eyebrow eyebrow--light">Internal project operations</span><h1>Move work.<br/><em>See everything.</em></h1><p>Live, role-scoped project delivery backed by PostgreSQL.</p></div></section><section className="auth-form-wrap"><div className="auth-form-card"><span className="section-index">ROLE / ACCESS</span><h2>Welcome back.</h2><p>Your database role decides which workspace opens.</p>{error && <div className="form-notice form-notice--error">{error}</div>}<form onSubmit={submit}><label>Work email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required/></label><button className="button button--primary button--block" disabled={busy}>{busy ? 'Connecting…' : 'Enter workspace'} <Icon name="arrow" size={17}/></button></form><div className="demo-accounts"><span>DEMO ACCOUNTS · CLICK TO FILL</span>{demos.map(([label, demoEmail, demoPassword]) => <button key={label} type="button" onClick={() => { setEmail(demoEmail); setPassword(demoPassword) }}><Avatar name={label}/><span><b>{label}</b><small>{demoEmail}<br/>Password: {demoPassword}</small></span></button>)}</div></div></section></main>
}

function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div className="dialog-backdrop" onMouseDown={(e) => e.target === e.currentTarget && close()}><section className="dialog"><div className="dialog-header"><h2>{title}</h2><button className="icon-button" onClick={close}><Icon name="close"/></button></div>{children}</section></div> }

function Workspace({ session, setSession }: { session: SessionResult; setSession: (value: SessionResult | null) => void }) {
  const role = session.user.role
  const allowedViews = useMemo<View[]>(() => role === 'ADMIN' ? ['dashboard','projects','tasks','clients','users','activity'] : role === 'PROJECT_MANAGER' ? ['dashboard','projects','tasks','activity'] : ['dashboard','tasks','activity'], [role])
  const roleRoot = role === 'ADMIN' ? '/admin' : role === 'PROJECT_MANAGER' ? '/pm' : '/developer'
  const initialView = (location.pathname.split('/')[2] || 'dashboard') as View
  const [view, setView] = useState<View>(allowedViews.includes(initialView) ? initialView : 'dashboard')
  const [filters, setFilters] = useState<Filters>(filtersFromUrl)
  const [dashboard, setDashboard] = useState<ApiDashboard | null>(null); const [tasks, setTasks] = useState<ApiTask[]>([]); const [projects, setProjects] = useState<ApiProject[]>([])
  const [clients, setClients] = useState<ApiClient[]>([]); const [developers, setDevelopers] = useState<ApiDeveloper[]>([]); const [users, setUsers] = useState<ApiUser[]>([])
  const [activity, setActivity] = useState<ApiActivity[]>([]); const [notifications, setNotifications] = useState<ApiNotification[]>([]); const [requests, setRequests] = useState<MemberRequest[]>([])
  const [connected, setConnected] = useState(false); const [error, setError] = useState(''); const [modal, setModal] = useState<'project'|'task'|'client'|'user'|'request'|null>(null); const [editingTask, setEditingTask] = useState<ApiTask|null>(null); const [menuOpen, setMenuOpen] = useState(false)

  const loadNotifications = useCallback(async () => setNotifications(await apiRequest<ApiNotification[]>('/notifications?pageSize=100', {}, session.accessToken)), [session.accessToken])
  const loadData = useCallback(async () => {
    try {
      const [dash, taskRows, events, notes] = await Promise.all([
        apiRequest<ApiDashboard>('/dashboard', {}, session.accessToken), apiRequest<ApiTask[]>(`/tasks?${queryFor(filters)}`, {}, session.accessToken),
        apiRequest<ApiActivity[]>('/activity?limit=20', {}, session.accessToken), apiRequest<ApiNotification[]>('/notifications?pageSize=100', {}, session.accessToken),
      ])
      setDashboard(dash); setTasks(taskRows); setActivity(events); setNotifications(notes)
      if (role !== 'DEVELOPER') {
        const [projectRows, clientRows, developerRows] = await Promise.all([apiRequest<ApiProject[]>('/projects', {}, session.accessToken), apiRequest<ApiClient[]>(role === 'ADMIN' ? '/clients' : '/lookups/clients', {}, session.accessToken), apiRequest<ApiDeveloper[]>('/lookups/developers', {}, session.accessToken)])
        setProjects(projectRows); setClients(clientRows); setDevelopers(developerRows)
      }
      if (role === 'ADMIN') setUsers(await apiRequest<ApiUser[]>('/users', {}, session.accessToken))
      if (role !== 'DEVELOPER') setRequests(await apiRequest<MemberRequest[]>('/member-requests', {}, session.accessToken))
      setError('')
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load workspace.') }
  }, [filters, role, session.accessToken])

  useEffect(() => { const timer = window.setTimeout(() => void loadData(), 0); return () => window.clearTimeout(timer) }, [loadData])
  useEffect(() => { if (view !== 'tasks') return; const p = new URLSearchParams(); for (const [key,value] of Object.entries(filters)) if (value) p.set(key,value); history.replaceState(null,'',`${roleRoot}/tasks${p.size ? `?${p}` : ''}`) }, [filters, roleRoot, view])
  useEffect(() => {
    const socket = io(SOCKET_URL, { transports: ['websocket'], auth: { accessToken: session.accessToken } })
    socket.on('connect', () => { setConnected(true); socket.emit('feed.watermark', async ({ sequence }: { sequence: string }) => { try { setActivity(await apiRequest<ApiActivity[]>(`/activity?through=${sequence}&limit=20`, {}, session.accessToken)) } catch { /* next event/load recovers */ } }) })
    socket.on('disconnect', () => setConnected(false))
    socket.on('activity.created', (event: ApiActivity) => { setActivity((rows) => [event, ...rows.filter((row) => row.id !== event.id)].slice(0,20)); void loadData() })
    socket.on('notifications.changed', () => void loadNotifications())
    socket.on('presence.changed', ({ onlineUsers }: { onlineUsers: number }) => setDashboard((value) => value ? { ...value, onlineUsers } : value))
    socket.on('task.access-revoked', () => void loadData())
    socket.on('session.revoked', () => setSession(null))
    socket.on('session.expired', async () => { try { setSession(await refreshSession()) } catch { setSession(null) } })
    return () => { socket.disconnect() }
  }, [loadData, loadNotifications, session.accessToken, setSession])

  const navigate = (next: View) => { setView(next); setMenuOpen(false); history.pushState(null,'',next === 'dashboard' ? roleRoot : `${roleRoot}/${next}`) }
  useEffect(() => { const onPopState = () => { const next = (location.pathname.split('/')[2] || 'dashboard') as View; if (allowedViews.includes(next)) setView(next) }; addEventListener('popstate', onPopState); return () => removeEventListener('popstate', onPopState) }, [allowedViews])
  const changeStatus = async (task: ApiTask, status: Status) => { if (status === task.status) return; try { const changed = await apiRequest<ApiTask>(`/tasks/${task.id}/status`, { method:'PATCH', body:JSON.stringify({ status, expectedVersion:task.version }) }, session.accessToken); setTasks((rows) => rows.map((row) => row.id === changed.id ? changed : row)); await loadData() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Status update failed.'); await loadData() } }
  const markRead = async (notification: ApiNotification) => { await apiRequest(`/notifications/${notification.id}/read`, { method:'PATCH' }, session.accessToken); await loadNotifications() }
  const markAll = async () => { await apiRequest('/notifications/read-all', { method:'POST', body:JSON.stringify({ through:new Date().toISOString() }) }, session.accessToken); await loadNotifications() }
  const logout = async () => { try { await endSession() } catch { /* clear local session regardless */ } setSession(null); history.replaceState(null,'','/login') }
  const openTasks = tasks.filter((task) => task.status !== 'DONE'); const unread = notifications.filter((note) => !note.readAt).length
  const editProject = async (project: ApiProject) => { const name = window.prompt('Project name', project.name)?.trim(); if (!name || name === project.name) return; await apiRequest(`/projects/${project.id}`, { method:'PATCH', body:JSON.stringify({ name }) }, session.accessToken); await loadData() }
  const editClient = async (client: ApiClient) => { const name = window.prompt('Client name', client.name)?.trim(); if (!name || name === client.name) return; await apiRequest(`/clients/${client.id}`, { method:'PATCH', body:JSON.stringify({ name }) }, session.accessToken); await loadData() }
  const patchUser = async (user: ApiUser, body: Record<string, unknown>) => { try { await apiRequest(`/users/${user.id}`, { method:'PATCH', body:JSON.stringify(body) }, session.accessToken); await loadData() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update user.') } }
  const resetPassword = async (user: ApiUser) => { const password = window.prompt(`New temporary password for ${user.email}:`); if (!password || password.length < 8) return; await patchUser(user, { password }) }

  const nav = allowedViews.map((id) => ({ id, label: id === 'dashboard' ? 'Overview' : id[0].toUpperCase()+id.slice(1) }))
  return <div className="app-shell">{menuOpen&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>}<aside className={menuOpen?'sidebar sidebar--open':'sidebar'}><div className="sidebar-brand"><Logo/><button className="mobile-close" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}><Icon name="close"/></button></div><div className="workspace-chip"><Avatar name={session.user.name}/><div><strong>{session.user.name}</strong><span>{role.replaceAll('_',' ')}</span></div></div><nav>{nav.map((item,index) => <button key={item.id} className={view===item.id?'nav-item nav-item--active':'nav-item'} onClick={() => navigate(item.id)}><span className="nav-index">0{index+1}</span><Icon name={item.id==='dashboard'?'grid':item.id==='projects'?'folder':item.id==='tasks'?'check':item.id==='users'?'users':item.id==='clients'?'building':'pulse'}/><span>{item.label}</span></button>)}</nav><div className="sidebar-foot"><span className="live-label"><i/> {connected?'Realtime connected':'Reconnecting'}</span><button onClick={logout}><Icon name="logout" size={16}/> Sign out</button></div></aside><main className="workspace-main"><header className="topbar"><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenuOpen(true)}><Icon name="menu"/></button><div className="topbar-label"><span>{role.replaceAll('_',' ')}</span><strong>Database-backed workspace</strong></div><div className="topbar-actions"><span className="connection-label"><i/> {connected?'Live':'Offline'}</span><details className="notification-wrap"><summary className="icon-button notification-button"><Icon name="bell"/>{unread>0&&<span>{unread}</span>}</summary><div className="notification-popover"><div className="notification-title"><strong>Notifications</strong><button onClick={markAll}>Mark all read</button></div>{notifications.map((note) => <article key={note.id} className={note.readAt?'notification-read':''}><div><strong>{note.type==='TASK_ASSIGNED'?'Task assigned':'Ready for review'}</strong><p>#{note.task.number} {note.task.title}</p><time>{relativeTime(note.createdAt)}</time></div>{!note.readAt&&<button onClick={() => void markRead(note)}>Mark read</button>}</article>)}{!notifications.length&&<div className="empty-state">No notifications</div>}</div></details><div className="manager-profile"><Avatar name={session.user.name}/><div><strong>{session.user.name}</strong><span>{role.replaceAll('_',' ')}</span></div></div></div></header><div className="page">{error&&<div className="form-notice form-notice--error">{error}</div>}
    {view==='dashboard'&&dashboard&&<><header className="page-header"><div><span className="eyebrow">Live portfolio</span><h1>Welcome, {session.user.name.split(' ')[0]}.</h1><p>All metrics below come from your authorized database scope.</p></div>{role==='PROJECT_MANAGER'&&<button className="button" onClick={()=>setModal('request')}><Icon name="users"/> Request member</button>}</header><section className="pm-summary"><article className="hero-metric"><span>{role==='DEVELOPER'?'ASSIGNED TO ME':'PROJECTS'}</span><strong>{role==='DEVELOPER'?dashboard.taskCount:dashboard.projectCount}</strong></article><article><span>OPEN TASKS</span><strong>{openTasks.length}</strong><small>{dashboard.byStatus.IN_REVIEW} in review</small></article><article className="danger-metric"><span>OVERDUE</span><strong>{dashboard.overdueCount}</strong></article><article className="week-metric"><span>{role==='ADMIN'?'ONLINE NOW':'DUE THIS WEEK'}</span><strong>{role==='ADMIN'?(dashboard.onlineUsers??0):dashboard.upcoming.length}</strong></article></section><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>{role==='PROJECT_MANAGER'?'Open tasks by priority':'Tasks by status'}</h2></div><div className="priority-breakdown">{Object.entries(role==='PROJECT_MANAGER'?dashboard.byPriority:dashboard.byStatus).map(([key,count])=><div key={key}><span>{role==='PROJECT_MANAGER'?key:statusLabel(key as Status)}</span><strong>{count}</strong></div>)}</div></section><section className="panel activity-panel"><div className="panel-heading"><h2>Latest activity</h2></div><ActivityList rows={activity}/></section></div></>}
    {view==='projects'&&<><header className="page-header"><div><span className="eyebrow">Authorized portfolio</span><h1>{role==='ADMIN'?'All projects':'My projects'}</h1></div><button className="button button--primary" onClick={()=>setModal('project')}><Icon name="plus"/> New project</button></header><section className="project-grid">{projects.map((project)=><article className="project-card" key={project.id}><Badge tone="active">ACTIVE</Badge><div><span className="task-id">{project.id.slice(0,8)}</span><h2>{project.name}</h2><p>{project.description}</p></div><dl><div><dt>Client</dt><dd>{project.client.name}</dd></div><div><dt>Manager</dt><dd>{project.createdBy.name}</dd></div><div><dt>Tasks</dt><dd>{project._count.tasks}</dd></div></dl><button className="text-button" onClick={()=>void editProject(project)}>Edit project <Icon name="arrow" size={14}/></button></article>)}</section></>}
    {view==='tasks'&&<><header className="page-header"><div><span className="eyebrow">Server-filtered queue</span><h1>{role==='DEVELOPER'?'My tasks':'Tasks'}</h1></div>{role!=='DEVELOPER'&&<button className="button button--primary" onClick={()=>setModal('task')}><Icon name="plus"/> New task</button>}</header><TaskFilters value={filters} change={setFilters}/><TaskTable rows={tasks} changeStatus={changeStatus} edit={role==='DEVELOPER'?undefined:setEditingTask}/></>}
    {view==='activity'&&<><header className="page-header"><div><span className="eyebrow">Database audit trail</span><h1>{role==='ADMIN'?'Global activity':'My activity'}</h1><p>Last 20 authorized events, with real-time updates and reconnect catch-up.</p></div></header><section className="panel"><ActivityList rows={activity}/></section></>}
    {view==='clients'&&<><header className="page-header"><div><span className="eyebrow">Client directory</span><h1>Clients</h1></div><button className="button button--primary" onClick={()=>setModal('client')}><Icon name="plus"/> New client</button></header><section className="admin-card-grid">{clients.map((client)=><article className="admin-directory-card" key={client.id}><Icon name="building"/><h2>{client.name}</h2><p>{client.contactName||'No contact'} · {client._count?.projects??0} projects</p><button className="text-button" onClick={()=>void editClient(client)}>Edit client <Icon name="arrow" size={14}/></button></article>)}</section></>}
    {view==='users'&&<><header className="page-header"><div><span className="eyebrow">Access control</span><h1>Team & roles</h1></div><button className="button button--primary" onClick={()=>setModal('user')}><Icon name="plus"/> Add member</button></header><section className="panel"><div className="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{user.role==='ADMIN'?'ADMIN':<select value={user.role} onChange={(e)=>void patchUser(user,{role:e.target.value})}><option value="PROJECT_MANAGER">PROJECT MANAGER</option><option value="DEVELOPER">DEVELOPER</option></select>}</td><td><Badge tone={user.isActive?'active':'neutral'}>{user.isActive?'ACTIVE':'INACTIVE'}</Badge></td><td><span className="row-actions">{user.role!=='ADMIN'&&<button onClick={()=>void patchUser(user,{isActive:!user.isActive})}>{user.isActive?'Deactivate':'Activate'}</button>}<button onClick={()=>void resetPassword(user)}>Reset password</button></span></td></tr>)}</tbody></table></div></section><section className="panel approval-panel"><div className="panel-heading"><h2>PM member requests</h2></div>{requests.map((request)=><article key={request.id}><strong>{request.name}</strong><p>{request.email} · {request.reason}</p><Badge tone={request.status.toLowerCase()}>{request.status}</Badge>{request.status==='PENDING'&&<span className="row-actions"><button onClick={()=>void reviewRequest(request,'REJECTED')}>Reject</button><button onClick={()=>void reviewRequest(request,'APPROVED')}>Approve</button></span>}</article>)}</section></>}
  </div></main>{modal&&<Editor kind={modal} role={role} projects={projects} clients={clients} developers={developers} close={()=>setModal(null)} save={async(path,body)=>{await apiRequest(path,{method:'POST',body:JSON.stringify(body)},session.accessToken);setModal(null);await loadData()}}/>}{editingTask&&<TaskEditor task={editingTask} developers={developers} close={()=>setEditingTask(null)} save={async(body)=>{await apiRequest(`/tasks/${editingTask.id}`,{method:'PATCH',body:JSON.stringify({...body,expectedVersion:editingTask.version})},session.accessToken);setEditingTask(null);await loadData()}}/>}</div>

  async function reviewRequest(request: MemberRequest, status: 'APPROVED'|'REJECTED') { const temporaryPassword = status==='APPROVED' ? window.prompt(`Temporary password for ${request.email} (8+ characters):`) : undefined; if(status==='APPROVED'&&(!temporaryPassword||temporaryPassword.length<8)) return; await apiRequest(`/member-requests/${request.id}`,{method:'PATCH',body:JSON.stringify(status==='APPROVED'?{status,temporaryPassword}:{status})},session.accessToken); await loadData() }
}

function TaskFilters({ value, change }: { value: Filters; change: (value: Filters) => void }) { return <div className="filter-bar"><label><span className="field-caption">Status</span><select value={value.status} onChange={(e)=>change({...value,status:e.target.value as Filters['status']})}><option value="">All</option>{(['TODO','IN_PROGRESS','IN_REVIEW','DONE'] as Status[]).map(v=><option key={v} value={v}>{statusLabel(v)}</option>)}</select></label><label><span className="field-caption">Priority</span><select value={value.priority} onChange={(e)=>change({...value,priority:e.target.value as Filters['priority']})}><option value="">All</option>{(['CRITICAL','HIGH','MEDIUM','LOW'] as Priority[]).map(v=><option key={v}>{v}</option>)}</select></label><label><span className="field-caption">Due from</span><input type="date" value={value.dueFrom} onChange={(e)=>change({...value,dueFrom:e.target.value})}/></label><label><span className="field-caption">Due to</span><input type="date" value={value.dueTo} onChange={(e)=>change({...value,dueTo:e.target.value})}/></label></div> }
function TaskTable({ rows, changeStatus, edit }: { rows: ApiTask[]; changeStatus: (task:ApiTask,status:Status)=>void; edit?: (task:ApiTask)=>void }) { return <section className="panel"><div className="table-scroll"><table className="task-table"><thead><tr><th>Task</th><th>Project</th><th>Assignee</th><th>Status</th><th>Priority</th><th>Due</th>{edit&&<th>Actions</th>}</tr></thead><tbody>{rows.map(task=><tr key={task.id}><td><span className="task-id">#{task.number}</span><strong>{task.title}</strong></td><td>{task.project.name}</td><td><span className="person-cell"><Avatar name={task.assignedDeveloper.name}/>{task.assignedDeveloper.name}</span></td><td><select className={`status-select status-select--${statusLabel(task.status).toLowerCase().replaceAll(' ','-')}`} value={task.status} onChange={(e)=>changeStatus(task,e.target.value as Status)}>{(['TODO','IN_PROGRESS','IN_REVIEW','DONE'] as Status[]).map(v=><option key={v} value={v}>{statusLabel(v)}</option>)}</select></td><td><span className={`priority priority--${task.priority.toLowerCase()}`}>{task.priority}</span></td><td className={task.isOverdue?'danger-text':''}>{new Date(task.dueAt).toLocaleDateString()}{task.isOverdue?' · OVERDUE':''}</td>{edit&&<td><button className="text-button" onClick={()=>edit(task)}>Edit</button></td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty-state"><strong>No tasks match</strong></div>}</div></section> }
function ActivityList({ rows }: { rows: ApiActivity[] }) { return <div className="activity-list activity-list--full">{rows.map(event=><article className="activity-item" key={event.id}><Avatar name={event.actor?.name||'System'}/><div><p><strong>{event.actor?.name||'System'}</strong> {activityText(event)}</p><time>{relativeTime(event.createdAt)} · {event.project.name}</time></div></article>)}{!rows.length&&<div className="empty-state">No activity in your scope.</div>}</div> }

function Editor({ kind, projects, clients, developers, close, save }: { kind:'project'|'task'|'client'|'user'|'request'; role:Role; projects:ApiProject[]; clients:ApiClient[]; developers:ApiDeveloper[]; close:()=>void; save:(path:string,body:unknown)=>Promise<void> }) {
  const [error,setError]=useState(''); const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(kind==='project')await save('/projects',{clientId:f.get('clientId'),name:f.get('name'),description:f.get('description')});if(kind==='task')await save(`/projects/${f.get('projectId')}/tasks`,{assignedDeveloperId:f.get('developerId'),title:f.get('name'),description:f.get('description'),priority:f.get('priority'),dueAt:new Date(`${f.get('dueAt')}T12:00:00+05:30`).toISOString()});if(kind==='client')await save('/clients',{name:f.get('name'),contactName:f.get('contactName')||undefined,contactEmail:f.get('contactEmail')||undefined});if(kind==='user')await save('/users',{name:f.get('name'),email:f.get('email'),password:f.get('password'),role:f.get('role')});if(kind==='request')await save('/member-requests',{name:f.get('name'),email:f.get('email'),reason:f.get('reason')})}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save.')}}
  return <Modal title={`New ${kind}`} close={close}><form onSubmit={submit}>{error&&<div className="form-notice form-notice--error">{error}</div>}{kind==='project'&&<><label>Name<input name="name" required/></label><label>Client<select name="clientId" required>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Description<textarea name="description" minLength={10} required/></label></>}{kind==='task'&&<><label>Title<input name="name" required/></label><label>Project<select name="projectId" required>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Developer<select name="developerId" required>{developers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Description<textarea name="description" minLength={5} required/></label><div className="form-grid"><label>Priority<select name="priority"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Due date<input name="dueAt" type="date" required/></label></div></>}{kind==='client'&&<><label>Name<input name="name" required/></label><label>Contact name<input name="contactName"/></label><label>Contact email<input name="contactEmail" type="email"/></label></>}{kind==='user'&&<><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Temporary password<input name="password" type="password" minLength={8} required/></label><label>Role<select name="role"><option value="PROJECT_MANAGER">PROJECT MANAGER</option><option value="DEVELOPER">DEVELOPER</option></select></label></>}{kind==='request'&&<><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Reason<textarea name="reason" minLength={10} required/></label></>}<div className="dialog-actions"><button type="button" className="button" onClick={close}>Cancel</button><button className="button button--primary">Save</button></div></form></Modal>
}

function TaskEditor({ task, developers, close, save }: { task:ApiTask; developers:ApiDeveloper[]; close:()=>void; save:(body:Record<string,unknown>)=>Promise<void> }) {
  const [error,setError]=useState(''); const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await save({title:f.get('title'),description:f.get('description'),assignedDeveloperId:f.get('developerId'),priority:f.get('priority'),dueAt:new Date(`${f.get('dueAt')}T12:00:00+05:30`).toISOString()})}catch(reason){setError(reason instanceof Error?reason.message:'Unable to update task.')}}
  return <Modal title={`Edit Task #${task.number}`} close={close}><form onSubmit={submit}>{error&&<div className="form-notice form-notice--error">{error}</div>}<label>Title<input name="title" defaultValue={task.title} required/></label><label>Developer<select name="developerId" defaultValue={task.assignedDeveloperId} required>{developers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Description<textarea name="description" defaultValue={task.description} minLength={5} required/></label><div className="form-grid"><label>Priority<select name="priority" defaultValue={task.priority}>{(['LOW','MEDIUM','HIGH','CRITICAL'] as Priority[]).map(value=><option key={value}>{value}</option>)}</select></label><label>Due date<input name="dueAt" type="date" defaultValue={task.dueAt.slice(0,10)} required/></label></div><div className="dialog-actions"><button type="button" className="button" onClick={close}>Cancel</button><button className="button button--primary">Save changes</button></div></form></Modal>
}

export default function ConnectedApp() {
  const [session,setSession]=useState<SessionResult|null>(null); const [loading,setLoading]=useState(true)
  useEffect(()=>{void refreshSession().then(setSession).catch(()=>undefined).finally(()=>setLoading(false))},[])
  useEffect(()=>{const onPop=()=>session&&setSession({...session});addEventListener('popstate',onPop);return()=>removeEventListener('popstate',onPop)},[session])
  if(loading)return <main className="auth-page"><section className="auth-form-wrap"><div className="auth-form-card"><h2>Restoring session…</h2></div></section></main>
  if(session?.user.mustChangePassword)return <ChangePassword session={session} done={()=>setSession({...session,user:{...session.user,mustChangePassword:false}})} logout={()=>setSession(null)}/>
  return session?<Workspace session={session} setSession={setSession}/>:<Login onLogin={(value)=>{setSession(value);history.replaceState(null,'',value.user.role==='ADMIN'?'/admin':value.user.role==='PROJECT_MANAGER'?'/pm':'/developer')}}/>
}

function ChangePassword({session,done,logout}:{session:SessionResult;done:()=>void;logout:()=>void}){const[error,setError]=useState('');const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const currentPassword=String(f.get('currentPassword'));const newPassword=String(f.get('newPassword'));if(newPassword!==f.get('confirmPassword'))return setError('New passwords do not match.');try{await apiRequest('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})},session.accessToken);done()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to change password.')}};return <main className="auth-page"><section className="auth-form-wrap"><div className="auth-form-card"><span className="section-index">SECURITY REQUIRED</span><h2>Change temporary password.</h2><p>Set a private password before entering the workspace.</p>{error&&<div className="form-notice form-notice--error">{error}</div>}<form onSubmit={submit}><label>Temporary password<input name="currentPassword" type="password" minLength={8} required/></label><label>New password<input name="newPassword" type="password" minLength={8} required/></label><label>Confirm password<input name="confirmPassword" type="password" minLength={8} required/></label><button className="button button--primary">Change password</button><button type="button" className="button" onClick={logout}>Cancel</button></form></div></section></main>}
